### ISSUE TITLE
Merge efforts

### ISSUE THREAD

**Issue by pascalwhoop** [Bost/corona_cases#1]
Hi Bost,
do you speak python? In that case we could merge efforts https://github.com/pascalwhoop/covid19-api
I saw you already have a mapping table of the names to country codes which is great! Maybe we can build a whole suit of APIs that offer useful data for frontend engineers building nice graphs.

What I built so far
- confirmed/deaths/recovered endpoints
- populations per country
- auto build / deploy on push to master on GCP App Engine
- CORS

I still wanted to make all country name references uniform and ensure the keys are all camelCase instead of strings with spaces in them in some cases. 

I have never written any closjure so it would take me a while to join this one. But if you don't like python that's also cool.

**Comment by Bost** [comment]
Some days ago I sent such a [PR](https://github.com/ExpDev07/coronavirus-tracker-api/pull/15) to that python repo. Since then I had to implement that feature myself in clojure anyway... :)

Anyway, both implementations work the same way, except that my [synonyms](https://github.com/Bost/corona_cases/blob/master/src/corona/countries.clj#L265) hash-map has a couple of more entries than the [corresponding](https://github.com/ExpDev07/coronavirus-tracker-api/blob/master/app/utils/countrycodes.py#L259) dictionary in python. And in the clojure implemetation I use `ZZZ` / `ZZ` instead of `XXX` / `XX` which I decided to use in the python implementation.

Could you create a PR with that difference and send it to the https://github.com/ExpDev07/coronavirus-tracker-api ? (And keep me up-to-date if you add something on top of that. Merci)
